work_dir: /workspace/potato/
report_to: wandb
tracker_project_name: potato
resume_from: null
load_from: null
debug: false
caching: false
# training setting
train:
  num_workers: 1
  seed: 1
  train_batch_size: 256
  num_epochs: 42
  gradient_accumulation_steps: 1
  grad_checkpointing: true
  gradient_clip: 0.1
  optimizer:
    lr: 1.0e-4
    type: AdamW
    weight_decay: 0.01
    eps: 1.0e-8
    betas: [0.9, 0.999]
  lr_schedule: constant
  lr_schedule_args:
    num_warmup_steps: 100
  local_save_vis: false # if save log image locally
  visualize: true
  eval_sampling_steps: 64
  log_interval: 32
  save_model_epochs: 1
  save_model_steps: 64
  work_dir: /workspace/potato
  online_metric: false
  eval_metric_step: 2000
  online_metric_dir: metric_helper
# model config
model:
  model: SanaMS_600M_P1_D28
  image_size: 512
  mixed_precision: bf16
  fp32_attention: true
  load_from:
  resume_from:
  aspect_ratio_type: ASPECT_RATIO_512
  multi_scale: true
  attn_type: linear
  linear_head_dim: 32
  ffn_type: glumbconv
  mlp_acts:
    - silu
    - silu
    - null
  mlp_ratio: 2.5
  use_pe: false
  qk_norm: false
  class_dropout_prob: 0.1
# VAE setting
vae:
  vae_type: dc-ae
  vae_pretrained: mit-han-lab/dc-ae-f32c32-sana-1.0
  scale_factor: 0.41407
  vae_latent_dim: 32
  vae_downsample_rate: 32
  sample_posterior: true
# text encoder
text_encoder:
  text_encoder_name: gemma-2-2b-it
  y_norm: true
  y_norm_scale_factor: 0.01
  model_max_length: 300
# Sana schedule Flow
scheduler:
  predict_v: true
  noise_schedule: linear_flow
  pred_sigma: false
  flow_shift: 1.0
  # logit-normal timestep
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  vis_sampler: flow_dpm-solver