data:
  data_dir: [ae3]
  image_size: 1024
  caption_proportion:
    prompt: 1
  external_caption_suffixes: ['', _InternVL2-26B, _VILA1-5-13B]
  external_clipscore_suffixes:
    - _InternVL2-26B_clip_score
    - _VILA1-5-13B_clip_score
    - _prompt_clip_score
  clip_thr_temperature: 0.1
  clip_thr: 25.0
  load_text_feat: false
  load_vae_feat: false
  transform: default_train
  type: SanaWebDatasetMS
  sort_dataset: false
# model config
model:
  model: SanaMS_1600M_P1_D20 #Potato
  image_size: 1024
  mixed_precision: fp16 # ['fp16', 'fp32', 'bf16']
  fp32_attention: true
  load_from: /home/Sana/epoch_16_step_6500.pth
  resume_from: 
  aspect_ratio_type: ASPECT_RATIO_1024
  multi_scale: true
  #pe_interpolation: 1.
  attn_type: linear
  ffn_type: glumbconv
  mlp_acts:
    - silu
    - silu
    -
  mlp_ratio: 2.5
  use_pe: false
  qk_norm: false
  class_dropout_prob: 0.1
  # PAG
  pag_applied_layers:
    - 8
# VAE setting
vae:
  vae_type: dc-ae
  vae_pretrained: mit-han-lab/dc-ae-f32c32-sana-1.0
  scale_factor: 0.41407
  vae_latent_dim: 32
  vae_downsample_rate: 32
  sample_posterior: true
# text encoder
text_encoder:
  text_encoder_name: gemma-2-2b-it
  y_norm: true
  y_norm_scale_factor: 0.01
  model_max_length: 300
  # CHI
  chi_prompt:
    - ''
# Sana schedule Flow
scheduler:
  predict_v: true
  noise_schedule: linear_flow
  pred_sigma: false
  flow_shift: 3.0
  # logit-normal timestep
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  vis_sampler: flow_dpm-solver
# training setting
train:
  num_workers: 1
  seed: 1
  train_batch_size: 16
  num_epochs: 8
  gradient_accumulation_steps: 1
  grad_checkpointing: true
  gradient_clip: 0.1
  optimizer:
    lr: 1.0e-4
    type: AdamW
    weight_decay: 0.01
    eps: 1.0e-8
    betas: [0.9, 0.999]
  lr_schedule: constant
  lr_schedule_args:
    num_warmup_steps: 400
  local_save_vis: true # if save log image locally
  visualize: true
  eval_sampling_steps: 1000
  log_interval: 32
  save_model_epochs: 1
  save_model_steps: 500
  work_dir: output/debug
  online_metric: false
  eval_metric_step: 2000
  online_metric_dir: metric_helper
  validation_prompts:
    - dog
    - cat
    - portrait photo of a girl, photograph, highly detailed face, depth of field
    - Self-portrait oil painting, a beautiful cyborg woman with golden hair, 8k
    - Astronaut in a jungle, cold color palette, muted colors, detailed, 8k
    - A photo of beautiful mountain with realistic sunset and blue lake, highly detailed, masterpiece
    - This photograph captures an up-close view of a mans face and upper torso against a plain white background with visible ceiling beams. The man has light skin, short, slightly tousled dark brown hair, and a scruffy beard.man,recoilme,1boy, realistic, male focus, solo, facial hair, striped shirt, photorealistic, shirt, striped clothes, asian, looking at viewer, indoors, upper body, from below
    - woman, solo, black hair, medium length hair, female focus, solo, bedroom, messy room, standing, black tube top, black panties, camel toe , peace sign, choker, top pulled down, taking a selfie
    - a half naked woman lying on her stomach on a bed, with her head resting on her arms. She appears to be in a relaxed state, possibly sleeping or resting. A cup of coffee is placed next to her on the bed, and a book is also present nearby. The scene suggests a cozy and comfortable atmosphere, with the woman enjoying her time in bed. 1girl, solo, book, realistic, brown hair, from above, jewelry, glasses, lying, long hair, earrings, sleeping
